### ISSUE TITLE
是否支持单独挂载到 dom 节点上

### ISSUE THREAD

**Issue by LuckyRyan-web** [ioing/lath#3]
因为我业务需要在一个 web 端的页面内嵌一个大小为 750 * 800 的移动端的页面，但是我又不想单独开一个移动端的项目用 lath 的 config.source.src 去引入。请问支持挂载到 web 端的 DOM 节点吗，比如整个页面挂载到 `<div id="lathAPP"></div>` 上

**Comment by ioing** [comment]
是支持的，可以使用<define-application> 标签创建根节点，也就是<div id="lathAPP"><define-application>...</define-application></div>

**Comment by ioing** [comment]
<defineApplication> 定义在哪，容器就创建在哪，和你理解的<div id="lathAPP"></div> 是一个意思
